[project]
name = "bigdatamadesmall"
version = "0.1.0"
description = "Workshop for Ukraine: Learning to use SQL through Python"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "duckdb>=1.1.3",
    "jupyterlab>=4.3.1",
    "pandas>=2.0.3",
    "pyarrow>=17.0.0",
]
